general {
  after_sleep_cmd = hyprctl dispatch dpms on
  before_sleep_cmd = loginctl lock-session
  ignore_dbus_inhibit = false
  lock_cmd = pidof hyprlock >/dev/null || hyprlock
}

listener {
  on-resume = ~/.config/hypr/scripts/hypridle_resume.sh
  on-timeout = ~/.config/hypr/scripts/hypridle_dim.sh
  timeout = 240
}

listener {
  on-timeout = ~/.config/hypr/scripts/hypridle_lock.sh
  timeout = 420
}

listener {
  on-resume = hyprctl dispatch dpms on
  on-timeout = hyprctl dispatch dpms off
  timeout = 480
}

listener {
  on-timeout = ~/.config/hypr/scripts/hypridle_suspend.sh
  timeout = 1200
}
