.pragma library

var emojiDbCache = null;

function getEmojiDatabase() {
    if (emojiDbCache)
        return emojiDbCache;
    emojiDbCache = [
            {char:"😀",name:"grinning face",keywords:"happy smile"},
            {char:"😂",name:"face with tears of joy",keywords:"laugh cry lol"},
            {char:"🥹",name:"face holding back tears",keywords:"emotional sad"},
            {char:"😍",name:"heart eyes",keywords:"love crush"},
            {char:"🥰",name:"smiling face with hearts",keywords:"love adore"},
            {char:"😘",name:"kissing face",keywords:"kiss love"},
            {char:"😎",name:"sunglasses face",keywords:"cool"},
            {char:"🤔",name:"thinking face",keywords:"think hmm"},
            {char:"😏",name:"smirking face",keywords:"smirk"},
            {char:"😢",name:"crying face",keywords:"sad tear"},
            {char:"😭",name:"loudly crying face",keywords:"cry sob"},
            {char:"😡",name:"angry face",keywords:"angry mad rage"},
            {char:"🤡",name:"clown face",keywords:"clown silly"},
            {char:"💀",name:"skull",keywords:"dead death"},
            {char:"👻",name:"ghost",keywords:"ghost boo"},
            {char:"👽",name:"alien",keywords:"alien ufo"},
            {char:"🤖",name:"robot",keywords:"robot bot"},
            {char:"😈",name:"smiling imp",keywords:"devil evil"},
            {char:"💩",name:"pile of poo",keywords:"poop shit"},
            {char:"🔥",name:"fire",keywords:"hot flame lit"},
            {char:"❤️",name:"red heart",keywords:"love heart"},
            {char:"💔",name:"broken heart",keywords:"sad breakup"},
            {char:"💯",name:"hundred points",keywords:"100 perfect score"},
            {char:"✨",name:"sparkles",keywords:"shine magic"},
            {char:"⭐",name:"star",keywords:"star favorite"},
            {char:"🌟",name:"glowing star",keywords:"shine glow"},
            {char:"💫",name:"dizzy",keywords:"star dizzy"},
            {char:"🎉",name:"party popper",keywords:"party celebrate"},
            {char:"🎊",name:"confetti ball",keywords:"party celebrate"},
            {char:"👍",name:"thumbs up",keywords:"like good ok"},
            {char:"👎",name:"thumbs down",keywords:"dislike bad"},
            {char:"👏",name:"clapping hands",keywords:"clap bravo"},
            {char:"🙏",name:"folded hands",keywords:"pray please thanks"},
            {char:"💪",name:"flexed biceps",keywords:"strong muscle"},
            {char:"🤝",name:"handshake",keywords:"deal agree"},
            {char:"✌️",name:"victory hand",keywords:"peace victory"},
            {char:"🤟",name:"love you gesture",keywords:"love rock"},
            {char:"👋",name:"waving hand",keywords:"wave hello bye"},
            {char:"🫡",name:"saluting face",keywords:"salute respect"},
            {char:"🫠",name:"melting face",keywords:"melt hot"},
            {char:"🥺",name:"pleading face",keywords:"puppy eyes please"},
            {char:"😴",name:"sleeping face",keywords:"sleep zzz tired"},
            {char:"🤯",name:"exploding head",keywords:"mind blown shock"},
            {char:"🥵",name:"hot face",keywords:"hot sweating"},
            {char:"🥶",name:"cold face",keywords:"cold freezing"},
            {char:"😱",name:"face screaming",keywords:"horror horror"},
            {char:"🫣",name:"face with peeking eye",keywords:"peek shy"},
            {char:"😳",name:"flushed face",keywords:"blush embarrassed"},
            {char:"🤓",name:"nerd face",keywords:"nerd glasses"},
            {char:"🧠",name:"brain",keywords:"brain smart think"},
            {char:"💻",name:"laptop",keywords:"computer laptop code"},
            {char:"🖥️",name:"desktop computer",keywords:"computer screen monitor"},
            {char:"⌨️",name:"keyboard",keywords:"keyboard type"},
            {char:"🖱️",name:"mouse",keywords:"mouse click"},
            {char:"📱",name:"mobile phone",keywords:"phone cell"},
            {char:"🎮",name:"video game",keywords:"game controller gaming"},
            {char:"🎵",name:"musical note",keywords:"music note song"},
            {char:"🎶",name:"musical notes",keywords:"music melody"},
            {char:"🎤",name:"microphone",keywords:"mic karaoke sing"},
            {char:"🎧",name:"headphone",keywords:"headphones music audio"},
            {char:"📷",name:"camera",keywords:"camera photo picture"},
            {char:"🎬",name:"clapper board",keywords:"movie film cinema"},
            {char:"📚",name:"books",keywords:"book study read"},
            {char:"✏️",name:"pencil",keywords:"write edit pencil"},
            {char:"📝",name:"memo",keywords:"note write document"},
            {char:"📎",name:"paperclip",keywords:"clip attach"},
            {char:"🔗",name:"link",keywords:"link chain url"},
            {char:"📌",name:"pushpin",keywords:"pin location"},
            {char:"🔒",name:"lock",keywords:"locked security password"},
            {char:"🔓",name:"unlock",keywords:"unlocked open"},
            {char:"🔑",name:"key",keywords:"key password"},
            {char:"⚙️",name:"gear",keywords:"settings config gear"},
            {char:"🔧",name:"wrench",keywords:"tool fix repair"},
            {char:"🛠️",name:"hammer and wrench",keywords:"tools build repair"},
            {char:"⚡",name:"high voltage",keywords:"electric lightning bolt"},
            {char:"💡",name:"light bulb",keywords:"idea lamp light"},
            {char:"🔍",name:"magnifying glass left",keywords:"search zoom find"},
            {char:"📊",name:"bar chart",keywords:"chart graph stats"},
            {char:"📈",name:"chart increasing",keywords:"growth up trending"},
            {char:"📉",name:"chart decreasing",keywords:"decline down"},
            {char:"✅",name:"check mark button",keywords:"done complete yes"},
            {char:"❌",name:"cross mark",keywords:"no wrong delete cancel"},
            {char:"⚠️",name:"warning",keywords:"warning caution alert"},
            {char:"🚀",name:"rocket",keywords:"rocket launch fast"},
            {char:"🌍",name:"globe europe africa",keywords:"world earth globe"},
            {char:"🏠",name:"house",keywords:"home house"},
            {char:"🌙",name:"crescent moon",keywords:"moon night"},
            {char:"☀️",name:"sun",keywords:"sun sunny bright"},
            {char:"🌈",name:"rainbow",keywords:"rainbow colors"},
            {char:"❄️",name:"snowflake",keywords:"cold ice snow winter nix"},
            {char:"🍕",name:"pizza",keywords:"pizza food"},
            {char:"🍔",name:"hamburger",keywords:"burger food"},
            {char:"☕",name:"hot beverage",keywords:"coffee tea"},
            {char:"🍺",name:"beer mug",keywords:"beer drink"},
            {char:"🐱",name:"cat face",keywords:"cat kitty meow"},
            {char:"🐶",name:"dog face",keywords:"dog puppy woof"},
            {char:"🐧",name:"penguin",keywords:"penguin linux tux"},
            {char:"🦊",name:"fox",keywords:"fox"},
            {char:"🐍",name:"snake",keywords:"snake python"},
            {char:"🦀",name:"crab",keywords:"crab rust"},
            // Nerd Font icons
            {char:"\u{f313}",name:"nix snowflake",keywords:"nix nixos linux"},
            {char:"\u{e795}",name:"terminal",keywords:"terminal console shell"},
            {char:"\u{f121}",name:"code",keywords:"code programming dev"},
            {char:"\u{f09b}",name:"github",keywords:"github git repo"},
            {char:"\u{f296}",name:"gitlab",keywords:"gitlab git"},
            {char:"\u{e702}",name:"vim",keywords:"vim neovim editor"},
            {char:"\u{f308}",name:"firefox",keywords:"firefox browser"},
            {char:"\u{f268}",name:"chrome",keywords:"chrome browser"},
            {char:"\u{e718}",name:"rust",keywords:"rust lang crab"},
            {char:"\u{e73c}",name:"python",keywords:"python snake"},
            {char:"\u{e781}",name:"haskell",keywords:"haskell functional"},
            {char:"\u{e61f}",name:"javascript",keywords:"javascript js node"},
            {char:"\u{e628}",name:"typescript",keywords:"typescript ts"},
            {char:"\u{f19a}",name:"docker",keywords:"docker container"},
            {char:"\u{f303}",name:"linux",keywords:"linux tux penguin"},
            {char:"\u{f17c}",name:"linux tux",keywords:"linux penguin"},
            {char:"\u{f27b}",name:"discord",keywords:"discord chat"},
            {char:"\u{f1d1}",name:"git branch",keywords:"git branch vcs"},
            {char:"\u{f1d2}",name:"git commit",keywords:"git commit"},
            {char:"\u{f1d3}",name:"git merge",keywords:"git merge"},
            {char:"\u{f07c}",name:"folder open",keywords:"folder directory"},
            {char:"\u{f15b}",name:"file",keywords:"file document"},
            {char:"\u{f1c9}",name:"file code",keywords:"source code file"},
            {char:"\u{f1c5}",name:"file image",keywords:"image picture photo file"},
            {char:"\u{f1c1}",name:"file pdf",keywords:"pdf document file"},
            {char:"\u{f0e7}",name:"bolt",keywords:"lightning bolt energy fast"},
            {char:"\u{f013}",name:"cog",keywords:"settings gear config"},
            {char:"\u{f0c5}",name:"copy",keywords:"copy duplicate clipboard"},
            {char:"\u{f0c4}",name:"scissors",keywords:"cut scissors"},
            {char:"\u{f0ea}",name:"clipboard",keywords:"paste clipboard"},
            {char:"\u{f2db}",name:"microchip",keywords:"cpu chip processor"},
            {char:"\u{f538}",name:"memory",keywords:"ram memory"},
            {char:"\u{f0a0}",name:"hdd",keywords:"disk drive storage"},
            {char:"\u{f1eb}",name:"wifi",keywords:"wifi wireless network"},
            {char:"\u{f293}",name:"bluetooth",keywords:"bluetooth wireless"},
            {char:"\u{f240}",name:"battery full",keywords:"battery power energy"},
        ];

    return emojiDbCache;
}

function search(term, normalizeText) {
    var normalizer = typeof normalizeText === "function" ? normalizeText : function(text) { return String(text || ""); };
    var normTerm = normalizer(term);
    var emojis = getEmojiDatabase();
    var results = [];
    for (var i = 0; i < emojis.length; i++) {
        var emoji = emojis[i];
        if (normTerm === "" || normalizer(emoji.name).indexOf(normTerm) >= 0 || (emoji.keywords && normalizer(emoji.keywords).indexOf(normTerm) >= 0)) {
            results.push({
                name: emoji.char + "  " + emoji.name,
                description: emoji.keywords || "",
                icon: "",
                type: "emoji",
                result: emoji.char,
                appId: "",
                appIdx: 0,
                extra: "",
                path: "",
                term: "",
                score: 0
            });
            if (results.length >= 40)
                break;
        }
    }
    return results;
}
