[package]
name = "zenith-cli"
version.workspace = true
edition = "2021"
authors.workspace = true
license.workspace = true

[[bin]]
name = "zenith"
path = "src/main.rs"

[dependencies]
zenith-core = { path = "../zenith-core" }
zenith-wayland = { path = "../zenith-wayland" }
tracing = "0.1"
wayland-client = "0.31"
smithay-client-toolkit = { version = "0.19", default-features = false, features = ["calloop"] }
calloop = "0.13"
calloop-wayland-source = "0.3"
notify = "8.0"
